version: '3.8'

networks:
  default:
    name: gateway
    external: true

services:
  web:
    build:
      dockerfile: ./.docker/web/Dockerfile
    stop_grace_period: 1s
    restart: unless-stopped
    networks:
      - default
    expose:
      - 3000
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-web.rule=Host(`${HOSTNAME_WEB}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-web.loadbalancer.server.port=3000"
